fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib.git
    inifile:
      repo: https://github.com/puppetlabs/puppetlabs-inifile.git
    epel:
      repo: https://github.com/voxpupuli/puppet-epel.git
    yumrepo_core:
      repo: https://github.com/puppetlabs/puppetlabs-yumrepo_core.git
  symlinks:
    fail2ban: "#{source_dir}"
