fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs/stdlib
    inifile:
      repo: puppetlabs/inifile
    epel:
      repo: puppet/epel
    yumrepo_core:
      repo: puppetlabs/yumrepo_core
  symlinks:
    fail2ban: "#{source_dir}"
