---
.rubocop.yml:
  profiles:
    strict:
      configs:
        RSpec/RepeatedExampleGroupBody:
          Enabled: false
        RSpec/RepeatedDescription:
          Enabled: false
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-11.yml:
  delete: true
spec/acceptance/nodesets/debian-12.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2004.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2204.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-2404.yml:
  delete: true
